const sampleData = {
  products: [
    {
      name: 'Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'The Smart Paris Polo Shirt Offers A Refined Twist On A Classic polo Staple. Crafted From Soft, Breathable Stretch Piqué, It Features Expert Design Elements Such As A Hidden Button Placket, Ribbed Accents, And A Tonal Crocodile. A Sophisticated, Timeless Piece.',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 59.99,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: "Men's Dress Shirts",
      description: 'The ideal hint of stretch meets expertly woven twill cloth in Supima®, the world\'s finest cotton. Featuring the Original Polo® Button-Down collar we invented, signature 6-Pleat Shirring® and barrel cuff. Technically superior, perfected over decades: our non-iron shirts keep you polished and virtually wrinkle-free all day, every day.We use American-grown Supima® cotton for its extra-long staple fibers that provide superior strength, softness, color retention, and longevity to our styles.',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 85.9,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: 'banner-2.jpg',
    },
    {
      name: 'Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'Look sharp with the timeless tailoring of this button-down collar dress shirt from Tommy Hilfiger\'s TH Flex collection. Cut from a crisp, cotton blend into a Classic Fit, its special stretch fabric offers optimal flexibility as you move through your busy day.A classic fit offers a generous cut throughout the chest and waist for overall ease; features standard armholes and fuller sleeves',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'The oxford shirt made its debut very early on in Ralph Lauren’s designs, and since then it has solidified its status as a pillar of the Polo look. Our fabric is developed with a secret wash that gives it instant character, ease, and a heathered softness. The formula is so unique, it’s been kept in a safe for more than three decades. In addition to details that evoke its prep-school inspiration, it offers a relaxed feel that produces what we call the perfect “rumple.” Today, Mr. Lauren continues to create countless variations of his iconic shirt, including this relaxed version that is finished with our multicolored signature Pony.',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'The oxford shirt made its debut very early on in Ralph Lauren’s designs, and since then it has solidified its status as a pillar of the Polo look. Our fabric is developed with a secret wash that gives it instant character, ease, and a heathered softness. The formula is so unique, it’s been kept in a safe for more than three decades. In addition to details that evoke its prep-school inspiration, it offers a relaxed feel that produces what we call the perfect “rumple.” Today, Mr. Lauren continues to create countless variations of his iconic shirt, including this short-sleeve version that is finished with our multicolored signature Pony.',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 79.99,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweat Shirts",
      description: 'The oxford shirt made its debut very early on in Ralph Lauren’s designs, and since then it has solidified its status as a pillar of the Polo look. Our fabric is developed with a secret wash that gives it instant character, ease, and a heathered softness. The formula is so unique, it’s been kept in a safe for more than three decades. In addition to details that evoke its prep-school inspiration, it offers a relaxed feel that produces what we call the perfect “rumple.” Today, Mr. Lauren continues to create countless variations of his iconic shirt, including this short-sleeve version that is finished with our multicolored signature Pony.',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 99.99,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
